.PHONY: clean All

All:
	@echo "----------Building project:[ tales - Debug ]----------"
	@"$(MAKE)" -f  "tales.mk"
clean:
	@echo "----------Cleaning project:[ tales - Debug ]----------"
	@"$(MAKE)" -f  "tales.mk" clean
